## try...catch 문법
```js
try{
    //...   
} catch(err){ // `에러 객체`
    //...
}
```
* c++의 기본 문법과 동일함
* try...catch는 런타임 에러에만 동작합니다. 
  * 문법 에러는 처리할 수 없습니다. 
* 동기적으로 동작하기 때문에 비동기적인 작업의 에러를 찾아 낼 수 없습니다. 
## 에러 객체
* 에러 객체는 두가지 주요 프로퍼티를 가집니다. 
* name 
  * 에러의 이름입니다.
  * 만약 정의되지 않은 변수때문에 발생한 에러이면 name은 `ReferenceError`값을 가집니다. 
* message
  * 에러 상세 내용을 담고 있는 문자 메시지
* stack
  * 현재 호출 스택. 에러를 유발한 중첩 호출들의 순서 정보를 가진 문자열로 디버깅 목적으로 사용
```js
try{
    lalala;
} catch(err){
    alert(err.name);
    alert(err.message);
    alert(err.stack);

    alert(err); // 에러를 찍으면 기본적으로 name : message 형태로 출력됨
}
```
## finally 문
* 에러가 없는 경우 try 실행 후 수행
* 에러가 있다면 catch 실행 후 수행